resources:
  pipelines:
    customers_orders_pipeline:
      name: "[${bundle.target} ${bundle.name}] Declarative Medallion Pipeline"

      catalog: ${var.catalog}
      schema: ${resources.schemas.bronze_schema.name}

      # Pipeline parameters (on code, this is accessed by the spark session configuration)
      configuration:
        landing_zone_volume: ${var.landing_zone_volume}
        bronze_schema: ${resources.schemas.bronze_schema.name}
        silver_schema: ${resources.schemas.silver_schema.name}
        gold_schema: ${resources.schemas.gold_schema.name}
      
      libraries:
        - notebook:
            path: ../src/pipeline_notebook.ipynb

      serverless: true